version: '3.9'

services:

  app:
    build: ./docker/app
    ports:
      - "8000:80"
    volumes:
      - ./src/:/app

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./src/:/app

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: amitube
      MYSQL_USER: aaaaa
      MYSQL_PASSWORD: aaaaa
      MYSQL_ROOT_PASSWORD: aaaaa
      TZ: 'Asia/Tokyo'
