name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/project

    steps:

    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'

    # Githubが公開するアクション actions/checkoutを利用すれば、ソースコードをチェックアウトできる
    - uses: actions/checkout@v3

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: laravel-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        env:
          PRIVATE_KEY:  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
                        NhAAAAAwEAAQAAAYEAnpAr2xj8/bVcwjW/ENQ8kzRG5T2fz21Dd01TDY2C87ImGq/O8f1b
                        n/S86dXWjMfDIjVkMPzBXwpJcz9Bptlrn/g9fItZ1mXg2hqvO4XPSjJvSLdw1cKhqTehp1
                        1nzMedyL5s7zKehzcoAfAVJgNotNmjzDu8Qjo7axILrkiVD059ZvQyBxQHIskvpJGtlVwc
                        /l/N5NLbknRU14pvsCDozD5va/QFvaTm/gyoVsY4omJg7uaUf7ruZEvW7HT9jmG1RC1Zpo
                        FTJgI9YM23savzcPrduyqtOcfYgBwLTsJU5X3jVx0qRIgJRSbGXbVOiPsE9i7th0qYQSmq
                        lM/hb7gW0ulUWsSqXu07luA82x7lbF1xfBGpAbAKMaNWMoifI7YEIdOVYqa0L12pNyJrTd
                        tJzwmttH2DQida2iMTb97upxjmdUYddgwzY800ehNsGtPahvUHEGwTuSFKgxys2E4qgjjv
                        /2ibk87aaKG1HK/+Sh0yvb+Z6AizCOH7qQ79vmzZAAAFsFhnYetYZ2HrAAAAB3NzaC1yc2
                        EAAAGBAJ6QK9sY/P21XMI1vxDUPJM0RuU9n89tQ3dNUw2NgvOyJhqvzvH9W5/0vOnV1ozH
                        wyI1ZDD8wV8KSXM/QabZa5/4PXyLWdZl4NoarzuFz0oyb0i3cNXCoak3oaddZ8zHnci+bO
                        8ynoc3KAHwFSYDaLTZo8w7vEI6O2sSC65IlQ9OfWb0MgcUByLJL6SRrZVcHP5fzeTS25J0
                        VNeKb7Ag6Mw+b2v0Bb2k5v4MqFbGOKJiYO7mlH+67mRL1ux0/Y5htUQtWaaBUyYCPWDNt7
                        Gr83D63bsqrTnH2IAcC07CVOV941cdKkSICUUmxl21Toj7BPYu7YdKmEEpqpTP4W+4FtLp
                        VFrEql7tO5bgPNse5WxdcXwRqQGwCjGjVjKInyO2BCHTlWKmtC9dqTcia03bSc8JrbR9g0
                        InWtojE2/e7qcY5nVGHXYMM2PNNHoTbBrT2ob1BxBsE7khSoMcrNhOKoI47/9om5PO2mih
                        tRyv/kodMr2/megIswjh+6kO/b5s2QAAAAMBAAEAAAGAQ7Hif1ZCQGDLGsEOcvVhbSk+8U
                        Tncwu/Z3I0OI+HblpK6U7Qp8CWewpmEuDwCceJOBQaU829EsHWDOVfNogRakj1mzP1JVL2
                        dbc5w8xDbPZuS1nBywkesptlIQqAM82vP9KIuHBgfPLf2j/xD3saG0flpd6E57NrxbD9Gq
                        mzNcc5Q5iSuTHkQAYrmHN3a9JZMIKfaQdapcKTrDfWqhfKu9QWBr02LDp4QdMOlYloCW+9
                        2ZDIqmWYvGoidm4WCFEPAVGuC80RP65OZacfuANdghVhwtA6XnCbR5BPCdjDfRFChV/xJZ
                        /YPYqy75a3OpYYOz99Wa3nLTy2NxzzW9QCNUsPh0BM1cB0206ULROcxV8SXbXF/0Vqe9hn
                        e8WOofM7SZ+iR2mPLgwhhi8kq+7SK57nfaw+dNDt8A/UsC3AXxF+VqsgYg3K4HKU+Q6fDy
                        TkG6vNCWHUTCDAIuLa4LWMCWSOGVyRSL8bEdK+KKE7PbQYFdJfyJyF9iKN8cM9OHu/AAAA
                        wAVjmDkCpIJ8/WysX7Nlvl7dxceLFA7aAx4GH0OKzz8xpyqWU7W5M5dbcprilO9tsTtdFn
                        BeH9OaTRyOYXHNLDdHKQFRRh4da4/yFOiCvscINY+BUqG1Mz+yohVqUt5V67jU4yeUDEjn
                        AhCGyWHVYpcMT2Y1kiEq8fvQPnqlDcUkJKg6wSKNdaiN/faQyi5NZ/XK+T7qA8rmK6WKCz
                        wERxAzM5U52bUvZhTi83er93QhlAWLwxL2OshKMl8qFL/HjgAAAMEAuaD3NqDykkyxduEv
                        hc3yzQKswFp9o/I/Hm0gmXmJh9cytYNQnWwz/rjrJFFBDuvyc6UwiqWc1ggRYFXjk1dNTB
                        qivOf3F5SHYNVn6/0reH/uQGy2jdBmeFL1/QTmUFEIU6vUphANMl8clVO/k47a6Uu+TaIm
                        EcogAs3TZa41+GovcWLUJJuXhm6xW64hSdU3BqM3BQyKMPVvUhU+JtsqdFd07BljZeTtgd
                        IT63V0RuOWEvJqbabSA5gbGZUoy82TAAAAwQDarIYIlgqOH3Ox/OpV76NY946OFtLHoYzF
                        nSlDIbkEl3bcFwCQsmwcdMKIDqzb+qJE6MA6ltaUwhdcVJoshAM+aeUQ+pPQGizFu2sZir
                        gLiWAu20Z2pGJ7B4YnvCTCKG8rNijlEU5KnvMV/c0usKy+kBcdXr3GkaQInoR7pAq95kDp
                        RtQZ/MWC5OkmE2vEHfzBLVKFHlAfmJUh0pKv2nKJ4RnjvUhfBmeyzVepvjh/8t/Gf2GZde
                        gdXGUpfRuGf2MAAAA4ZWMyLXVzZXJAaXAtMTcyLTMxLTAtMjM5LmFwLW5vcnRoZWFzdC0x
                        LmNvbXB1dGUuaW50ZXJuYWwBAgM=
          USER_NAME: ec2-user
          HOST_NAME: ec2-35-78-249-46.ap-northeast-1.compute.amazonaws.com
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-35-78-249-46.ap-northeast-1.compute.amazonaws.com 'cd /var/www/ci'